### ISSUE TITLE
Issue with link to test sets

### ISSUE THREAD

**Issue by noeedc** [hzwer/CVPR2023-DMVFN#16]
Hello ! There seems to be an issue with the google drive link to your test sets. Also I was wondering how do you train the model on custom dataset? 
Thank you !

**Comment by hzwer** [comment]
Fixed. And we did not try training on custom dataset, sorry.

**Comment by noeedc** [comment]
Thank you for the fix, @hzwer ! The new links work. Closing it the issue now.
